name: app_review_plus_example
description: Demonstrates how to use the app_review plugin.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  app_review_plus:
    path: ../

flutter:
  uses-material-design: true
